package provider

// Note:  This file is automatically generated.  Manually made changes
// will be overwritten when the provider is generated.

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/PaloAltoNetworks/pango"
	"github.com/PaloAltoNetworks/pango/device/profiles/datafiltering"
	pangoutil "github.com/PaloAltoNetworks/pango/util"

	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	rsschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	sdkmanager "github.com/PaloAltoNetworks/terraform-provider-panos/internal/manager"
)

// Generate Terraform Data Source object.
var (
	_ datasource.DataSource              = &DataFilteringProfileDataSource{}
	_ datasource.DataSourceWithConfigure = &DataFilteringProfileDataSource{}
)

func NewDataFilteringProfileDataSource() datasource.DataSource {
	return &DataFilteringProfileDataSource{}
}

type DataFilteringProfileDataSource struct {
	client  *pango.Client
	manager *sdkmanager.EntryObjectManager[*datafiltering.Entry, datafiltering.Location, *datafiltering.Service]
}

type DataFilteringProfileDataSourceFilter struct {
	// TODO: Generate Data Source filter via function
}

type DataFilteringProfileDataSourceModel struct {
	Location        types.Object `tfsdk:"location"`
	Name            types.String `tfsdk:"name"`
	DataCapture     types.Bool   `tfsdk:"data_capture"`
	Description     types.String `tfsdk:"description"`
	DisableOverride types.String `tfsdk:"disable_override"`
	Rules           types.List   `tfsdk:"rules"`
}
type DataFilteringProfileDataSourceRulesObject struct {
	Name           types.String `tfsdk:"name"`
	DataObject     types.String `tfsdk:"data_object"`
	Direction      types.String `tfsdk:"direction"`
	AlertThreshold types.Int64  `tfsdk:"alert_threshold"`
	BlockThreshold types.Int64  `tfsdk:"block_threshold"`
	LogSeverity    types.String `tfsdk:"log_severity"`
	Application    types.List   `tfsdk:"application"`
	FileType       types.List   `tfsdk:"file_type"`
}

func (o *DataFilteringProfileDataSourceModel) AttributeTypes() map[string]attr.Type {

	var locationObj DataFilteringProfileLocation

	var rulesObj *DataFilteringProfileDataSourceRulesObject
	return map[string]attr.Type{
		"location": types.ObjectType{
			AttrTypes: locationObj.AttributeTypes(),
		},
		"name":             types.StringType,
		"data_capture":     types.BoolType,
		"description":      types.StringType,
		"disable_override": types.StringType,
		"rules": types.ListType{
			ElemType: types.ObjectType{
				AttrTypes: rulesObj.AttributeTypes(),
			},
		},
	}
}

func (o DataFilteringProfileDataSourceModel) AncestorName() string {
	return ""
}

func (o DataFilteringProfileDataSourceModel) EntryName() *string {
	return nil
}
func (o *DataFilteringProfileDataSourceRulesObject) AttributeTypes() map[string]attr.Type {

	return map[string]attr.Type{
		"name":            types.StringType,
		"data_object":     types.StringType,
		"direction":       types.StringType,
		"alert_threshold": types.Int64Type,
		"block_threshold": types.Int64Type,
		"log_severity":    types.StringType,
		"application": types.ListType{
			ElemType: types.StringType,
		},
		"file_type": types.ListType{
			ElemType: types.StringType,
		},
	}
}

func (o DataFilteringProfileDataSourceRulesObject) AncestorName() string {
	return "rules"
}

func (o DataFilteringProfileDataSourceRulesObject) EntryName() *string {
	return o.Name.ValueStringPointer()
}

func (o *DataFilteringProfileDataSourceModel) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **datafiltering.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	dataCapture_value := o.DataCapture.ValueBoolPointer()
	description_value := o.Description.ValueStringPointer()
	disableOverride_value := o.DisableOverride.ValueStringPointer()
	var rules_tf_entries []DataFilteringProfileDataSourceRulesObject
	var rules_pango_entries []datafiltering.Rules
	{
		d := o.Rules.ElementsAs(ctx, &rules_tf_entries, false)
		diags.Append(d...)
		if diags.HasError() {
			return diags
		}
		for _, elt := range rules_tf_entries {
			var entry *datafiltering.Rules
			diags.Append(elt.CopyToPango(ctx, client, append(ancestors, elt), &entry, ev)...)
			if diags.HasError() {
				return diags
			}
			rules_pango_entries = append(rules_pango_entries, *entry)
		}
	}

	if (*obj) == nil {
		*obj = new(datafiltering.Entry)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).DataCapture = dataCapture_value
	(*obj).Description = description_value
	(*obj).DisableOverride = disableOverride_value
	(*obj).Rules = rules_pango_entries

	return diags
}
func (o *DataFilteringProfileDataSourceRulesObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **datafiltering.Rules, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	dataObject_value := o.DataObject.ValueStringPointer()
	direction_value := o.Direction.ValueStringPointer()
	alertThreshold_value := o.AlertThreshold.ValueInt64Pointer()
	blockThreshold_value := o.BlockThreshold.ValueInt64Pointer()
	logSeverity_value := o.LogSeverity.ValueStringPointer()
	var application_pango_entries []string
	if !o.Application.IsUnknown() && !o.Application.IsNull() {
		object_entries := make([]types.String, 0, len(o.Application.Elements()))
		diags.Append(o.Application.ElementsAs(ctx, &object_entries, false)...)
		if diags.HasError() {
			diags.AddError("Explicit Error", "Failed something")
			return diags
		}

		for _, elt := range object_entries {
			application_pango_entries = append(application_pango_entries, elt.ValueString())
		}
	}
	var fileType_pango_entries []string
	if !o.FileType.IsUnknown() && !o.FileType.IsNull() {
		object_entries := make([]types.String, 0, len(o.FileType.Elements()))
		diags.Append(o.FileType.ElementsAs(ctx, &object_entries, false)...)
		if diags.HasError() {
			diags.AddError("Explicit Error", "Failed something")
			return diags
		}

		for _, elt := range object_entries {
			fileType_pango_entries = append(fileType_pango_entries, elt.ValueString())
		}
	}

	if (*obj) == nil {
		*obj = new(datafiltering.Rules)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).DataObject = dataObject_value
	(*obj).Direction = direction_value
	(*obj).AlertThreshold = alertThreshold_value
	(*obj).BlockThreshold = blockThreshold_value
	(*obj).LogSeverity = logSeverity_value
	(*obj).Application = application_pango_entries
	(*obj).FileType = fileType_pango_entries

	return diags
}

func (o *DataFilteringProfileDataSourceModel) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *datafiltering.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var rules_list types.List
	{
		var rules_tf_entries []DataFilteringProfileDataSourceRulesObject
		if !o.Rules.IsNull() {
			diags.Append(o.Rules.ElementsAs(ctx, &rules_tf_entries, false)...)
			if diags.HasError() {
				return diags
			}
		}

		for idx, elt := range obj.Rules {
			entry := DataFilteringProfileDataSourceRulesObject{
				Name: types.StringValue(elt.Name),
			}
			if idx < len(rules_tf_entries) {
				entry = rules_tf_entries[idx]
			}

			diags.Append(entry.CopyFromPango(ctx, client, append(ancestors, entry), &elt, ev)...)
			if diags.HasError() {
				return diags
			}

			if idx < len(rules_tf_entries) {
				rules_tf_entries[idx] = entry
			} else {
				rules_tf_entries = append(rules_tf_entries, entry)
			}
		}
		var list_diags diag.Diagnostics
		schemaType := o.getTypeFor("rules")
		rules_list, list_diags = types.ListValueFrom(ctx, schemaType, rules_tf_entries)
		diags.Append(list_diags...)
	}

	var dataCapture_value types.Bool
	if obj.DataCapture != nil {
		dataCapture_value = types.BoolValue(*obj.DataCapture)
	}
	var description_value types.String
	if obj.Description != nil {
		description_value = types.StringValue(*obj.Description)
	}
	var disableOverride_value types.String
	if obj.DisableOverride != nil {
		disableOverride_value = types.StringValue(*obj.DisableOverride)
	}
	o.Name = types.StringValue(obj.Name)
	o.DataCapture = dataCapture_value
	o.Description = description_value
	o.DisableOverride = disableOverride_value
	o.Rules = rules_list

	return diags
}

func (o *DataFilteringProfileDataSourceRulesObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *datafiltering.Rules, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var application_list types.List
	{
		var list_diags diag.Diagnostics

		entries := make([]string, 0)
		if o.Application.IsNull() || len(obj.Application) > 0 {
			entries = obj.Application
		}

		application_list, list_diags = types.ListValueFrom(ctx, types.StringType, entries)
		diags.Append(list_diags...)
		if diags.HasError() {
			return diags
		}
	}
	var fileType_list types.List
	{
		var list_diags diag.Diagnostics

		entries := make([]string, 0)
		if o.FileType.IsNull() || len(obj.FileType) > 0 {
			entries = obj.FileType
		}

		fileType_list, list_diags = types.ListValueFrom(ctx, types.StringType, entries)
		diags.Append(list_diags...)
		if diags.HasError() {
			return diags
		}
	}

	var dataObject_value types.String
	if obj.DataObject != nil {
		dataObject_value = types.StringValue(*obj.DataObject)
	}
	var direction_value types.String
	if obj.Direction != nil {
		direction_value = types.StringValue(*obj.Direction)
	}
	var alertThreshold_value types.Int64
	if obj.AlertThreshold != nil {
		alertThreshold_value = types.Int64Value(*obj.AlertThreshold)
	}
	var blockThreshold_value types.Int64
	if obj.BlockThreshold != nil {
		blockThreshold_value = types.Int64Value(*obj.BlockThreshold)
	}
	var logSeverity_value types.String
	if obj.LogSeverity != nil {
		logSeverity_value = types.StringValue(*obj.LogSeverity)
	}
	o.Name = types.StringValue(obj.Name)
	o.DataObject = dataObject_value
	o.Direction = direction_value
	o.AlertThreshold = alertThreshold_value
	o.BlockThreshold = blockThreshold_value
	o.LogSeverity = logSeverity_value
	o.Application = application_list
	o.FileType = fileType_list

	return diags
}

func (o *DataFilteringProfileDataSourceModel) resourceXpathParentComponents() ([]string, error) {
	var components []string
	return components, nil
}

func DataFilteringProfileDataSourceSchema() dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{

			"location": DataFilteringProfileDataSourceLocationSchema(),

			"name": dsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"data_capture": dsschema.BoolAttribute{
				Description: "",
				Optional:    true,
				Computed:    true,
			},

			"description": dsschema.StringAttribute{
				Description: "",
				Optional:    true,
				Computed:    true,
			},

			"disable_override": dsschema.StringAttribute{
				Description: "disable object override in child device groups",
				Optional:    true,
				Computed:    true,
			},

			"rules": dsschema.ListNestedAttribute{
				Description:  "",
				Optional:     true,
				Computed:     true,
				NestedObject: DataFilteringProfileDataSourceRulesSchema(),
			},
		},
	}
}

func (o *DataFilteringProfileDataSourceModel) getTypeFor(name string) attr.Type {
	schema := DataFilteringProfileDataSourceSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case dsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case dsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func DataFilteringProfileDataSourceRulesSchema() dsschema.NestedAttributeObject {
	return dsschema.NestedAttributeObject{
		Attributes: map[string]dsschema.Attribute{

			"name": dsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"data_object": dsschema.StringAttribute{
				Description: "",
				Optional:    true,
				Computed:    true,
			},

			"direction": dsschema.StringAttribute{
				Description: "",
				Optional:    true,
				Computed:    true,
			},

			"alert_threshold": dsschema.Int64Attribute{
				Description: "",
				Optional:    true,
				Computed:    true,
			},

			"block_threshold": dsschema.Int64Attribute{
				Description: "",
				Optional:    true,
				Computed:    true,
			},

			"log_severity": dsschema.StringAttribute{
				Description: "",
				Optional:    true,
				Computed:    true,
			},

			"application": dsschema.ListAttribute{
				Description: "",
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
			},

			"file_type": dsschema.ListAttribute{
				Description: "",
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
			},
		},
	}
}

func (o *DataFilteringProfileDataSourceRulesObject) getTypeFor(name string) attr.Type {
	schema := DataFilteringProfileDataSourceRulesSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case dsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case dsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func DataFilteringProfileDataSourceLocationSchema() rsschema.Attribute {
	return DataFilteringProfileLocationSchema()
}

// Metadata returns the data source type name.
func (d *DataFilteringProfileDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_data_filtering_profile"
}

// Schema defines the schema for this data source.
func (d *DataFilteringProfileDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = DataFilteringProfileDataSourceSchema()
}

// Configure prepares the struct.
func (d *DataFilteringProfileDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerData := req.ProviderData.(*ProviderData)
	d.client = providerData.Client
	specifier, _, err := datafiltering.Versioning(d.client.Versioning())
	if err != nil {
		resp.Diagnostics.AddError("Failed to configure SDK client", err.Error())
		return
	}
	batchSize := providerData.MultiConfigBatchSize
	d.manager = sdkmanager.NewEntryObjectManager[*datafiltering.Entry, datafiltering.Location, *datafiltering.Service](d.client, datafiltering.NewService(d.client), batchSize, specifier, datafiltering.SpecMatches)
}
func (o *DataFilteringProfileDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {

	var state DataFilteringProfileDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var encryptedValues []byte
	ev, err := NewEncryptedValuesManager(encryptedValues, true)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	var location datafiltering.Location

	{
		var terraformLocation DataFilteringProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Shared.IsNull() {
			location.Shared = &datafiltering.SharedLocation{}
			var innerLocation DataFilteringProfileSharedLocation
			resp.Diagnostics.Append(terraformLocation.Shared.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.DeviceGroup.IsNull() {
			location.DeviceGroup = &datafiltering.DeviceGroupLocation{}
			var innerLocation DataFilteringProfileDeviceGroupLocation
			resp.Diagnostics.Append(terraformLocation.DeviceGroup.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.DeviceGroup.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.DeviceGroup.DeviceGroup = innerLocation.Name.ValueString()
		}
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource read", map[string]any{
		"resource_name": "panos_data_filtering_profile_resource",
		"function":      "Read",
		"name":          state.Name.ValueString(),
	})

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	object, err := o.manager.Read(ctx, location, components, state.Name.ValueString())
	if err != nil {
		if errors.Is(err, sdkmanager.ErrObjectNotFound) {
			resp.Diagnostics.AddError("Error reading data", err.Error())
		} else {
			resp.Diagnostics.AddError("Error reading entry", err.Error())
		}
		return
	}

	copy_diags := state.CopyFromPango(ctx, o.client, nil, object, ev)
	resp.Diagnostics.Append(copy_diags...)

	/*
			// Keep the timeouts.
		    // TODO: This won't work for state import.
			state.Timeouts = state.Timeouts
	*/

	state.Location = state.Location

	// Done.
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)

}

// Generate Terraform Resource object
var (
	_ resource.Resource                = &DataFilteringProfileResource{}
	_ resource.ResourceWithConfigure   = &DataFilteringProfileResource{}
	_ resource.ResourceWithImportState = &DataFilteringProfileResource{}
)

func NewDataFilteringProfileResource() resource.Resource {
	if _, found := resourceFuncMap["panos_data_filtering_profile"]; !found {
		resourceFuncMap["panos_data_filtering_profile"] = resourceFuncs{
			CreateImportId: DataFilteringProfileImportStateCreator,
		}
	}
	return &DataFilteringProfileResource{}
}

type DataFilteringProfileResource struct {
	client  *pango.Client
	manager *sdkmanager.EntryObjectManager[*datafiltering.Entry, datafiltering.Location, *datafiltering.Service]
}

func DataFilteringProfileResourceLocationSchema() rsschema.Attribute {
	return DataFilteringProfileLocationSchema()
}

type DataFilteringProfileResourceModel struct {
	Location        types.Object `tfsdk:"location"`
	Name            types.String `tfsdk:"name"`
	DataCapture     types.Bool   `tfsdk:"data_capture"`
	Description     types.String `tfsdk:"description"`
	DisableOverride types.String `tfsdk:"disable_override"`
	Rules           types.List   `tfsdk:"rules"`
}
type DataFilteringProfileResourceRulesObject struct {
	Name           types.String `tfsdk:"name"`
	DataObject     types.String `tfsdk:"data_object"`
	Direction      types.String `tfsdk:"direction"`
	AlertThreshold types.Int64  `tfsdk:"alert_threshold"`
	BlockThreshold types.Int64  `tfsdk:"block_threshold"`
	LogSeverity    types.String `tfsdk:"log_severity"`
	Application    types.List   `tfsdk:"application"`
	FileType       types.List   `tfsdk:"file_type"`
}

func (o *DataFilteringProfileResourceModel) ValidateConfig(ctx context.Context, resp *resource.ValidateConfigResponse, path path.Path) {
	if !o.Rules.IsUnknown() && !o.Rules.IsNull() {
		var elements []DataFilteringProfileResourceRulesObject
		diags := o.Rules.ElementsAs(ctx, &elements, false)
		if diags.HasError() {
			resp.Diagnostics.Append(diags...)
		} else {
			for i, element := range elements {
				element.ValidateConfig(ctx, resp, path.AtName("rules").AtListIndex(i))
			}
		}
	}
}

func (o *DataFilteringProfileResourceRulesObject) ValidateConfig(ctx context.Context, resp *resource.ValidateConfigResponse, path path.Path) {
}

func (o *DataFilteringProfileResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {

	var resource DataFilteringProfileResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &resource)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resource.ValidateConfig(ctx, resp, path.Empty())
}

// <ResourceSchema>

func DataFilteringProfileResourceSchema() rsschema.Schema {
	return rsschema.Schema{
		Attributes: map[string]rsschema.Attribute{

			"location": DataFilteringProfileResourceLocationSchema(),

			"name": rsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"data_capture": rsschema.BoolAttribute{
				Description: "",
				Optional:    true,
			},

			"description": rsschema.StringAttribute{
				Description: "",
				Optional:    true,
			},

			"disable_override": rsschema.StringAttribute{
				Description: "disable object override in child device groups",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("no"),

				Validators: []validator.String{
					stringvalidator.OneOf([]string{
						"yes",
						"no",
					}...),
				},
			},

			"rules": rsschema.ListNestedAttribute{
				Description:  "",
				Optional:     true,
				NestedObject: DataFilteringProfileResourceRulesSchema(),
			},
		},
	}
}

func (o *DataFilteringProfileResourceModel) getTypeFor(name string) attr.Type {
	schema := DataFilteringProfileResourceSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case rsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case rsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func DataFilteringProfileResourceRulesSchema() rsschema.NestedAttributeObject {
	return rsschema.NestedAttributeObject{
		Attributes: map[string]rsschema.Attribute{

			"name": rsschema.StringAttribute{
				Description: "",
				Required:    true,
			},

			"data_object": rsschema.StringAttribute{
				Description: "",
				Optional:    true,
			},

			"direction": rsschema.StringAttribute{
				Description: "",
				Optional:    true,
			},

			"alert_threshold": rsschema.Int64Attribute{
				Description: "",
				Optional:    true,
				Computed:    true,
				Default:     int64default.StaticInt64(1),
			},

			"block_threshold": rsschema.Int64Attribute{
				Description: "",
				Optional:    true,
				Computed:    true,
				Default:     int64default.StaticInt64(1),
			},

			"log_severity": rsschema.StringAttribute{
				Description: "",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("informational"),
			},

			"application": rsschema.ListAttribute{
				Description: "",
				Optional:    true,
				ElementType: types.StringType,
			},

			"file_type": rsschema.ListAttribute{
				Description: "",
				Optional:    true,
				ElementType: types.StringType,
			},
		},
	}
}

func (o *DataFilteringProfileResourceRulesObject) getTypeFor(name string) attr.Type {
	schema := DataFilteringProfileResourceRulesSchema()
	if attr, ok := schema.Attributes[name]; !ok {
		panic(fmt.Sprintf("could not resolve schema for attribute %s", name))
	} else {
		switch attr := attr.(type) {
		case rsschema.ListNestedAttribute:
			return attr.NestedObject.Type()
		case rsschema.MapNestedAttribute:
			return attr.NestedObject.Type()
		default:
			return attr.GetType()
		}
	}

	panic("unreachable")
}

func (o *DataFilteringProfileResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_data_filtering_profile"
}

func (o *DataFilteringProfileResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = DataFilteringProfileResourceSchema()
}

// </ResourceSchema>

func (o *DataFilteringProfileResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData := req.ProviderData.(*ProviderData)
	o.client = providerData.Client
	specifier, _, err := datafiltering.Versioning(o.client.Versioning())
	if err != nil {
		resp.Diagnostics.AddError("Failed to configure SDK client", err.Error())
		return
	}
	batchSize := providerData.MultiConfigBatchSize
	o.manager = sdkmanager.NewEntryObjectManager[*datafiltering.Entry, datafiltering.Location, *datafiltering.Service](o.client, datafiltering.NewService(o.client), batchSize, specifier, datafiltering.SpecMatches)
}

func (o *DataFilteringProfileResourceModel) AttributeTypes() map[string]attr.Type {

	var locationObj DataFilteringProfileLocation

	var rulesObj *DataFilteringProfileResourceRulesObject
	return map[string]attr.Type{
		"location": types.ObjectType{
			AttrTypes: locationObj.AttributeTypes(),
		},
		"name":             types.StringType,
		"data_capture":     types.BoolType,
		"description":      types.StringType,
		"disable_override": types.StringType,
		"rules": types.ListType{
			ElemType: types.ObjectType{
				AttrTypes: rulesObj.AttributeTypes(),
			},
		},
	}
}

func (o DataFilteringProfileResourceModel) AncestorName() string {
	return ""
}

func (o DataFilteringProfileResourceModel) EntryName() *string {
	return nil
}
func (o *DataFilteringProfileResourceRulesObject) AttributeTypes() map[string]attr.Type {

	return map[string]attr.Type{
		"name":            types.StringType,
		"data_object":     types.StringType,
		"direction":       types.StringType,
		"alert_threshold": types.Int64Type,
		"block_threshold": types.Int64Type,
		"log_severity":    types.StringType,
		"application": types.ListType{
			ElemType: types.StringType,
		},
		"file_type": types.ListType{
			ElemType: types.StringType,
		},
	}
}

func (o DataFilteringProfileResourceRulesObject) AncestorName() string {
	return "rules"
}

func (o DataFilteringProfileResourceRulesObject) EntryName() *string {
	return o.Name.ValueStringPointer()
}

func (o *DataFilteringProfileResourceModel) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **datafiltering.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	dataCapture_value := o.DataCapture.ValueBoolPointer()
	description_value := o.Description.ValueStringPointer()
	disableOverride_value := o.DisableOverride.ValueStringPointer()
	var rules_tf_entries []DataFilteringProfileResourceRulesObject
	var rules_pango_entries []datafiltering.Rules
	{
		d := o.Rules.ElementsAs(ctx, &rules_tf_entries, false)
		diags.Append(d...)
		if diags.HasError() {
			return diags
		}
		for _, elt := range rules_tf_entries {
			var entry *datafiltering.Rules
			diags.Append(elt.CopyToPango(ctx, client, append(ancestors, elt), &entry, ev)...)
			if diags.HasError() {
				return diags
			}
			rules_pango_entries = append(rules_pango_entries, *entry)
		}
	}

	if (*obj) == nil {
		*obj = new(datafiltering.Entry)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).DataCapture = dataCapture_value
	(*obj).Description = description_value
	(*obj).DisableOverride = disableOverride_value
	(*obj).Rules = rules_pango_entries

	return diags
}
func (o *DataFilteringProfileResourceRulesObject) CopyToPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj **datafiltering.Rules, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	dataObject_value := o.DataObject.ValueStringPointer()
	direction_value := o.Direction.ValueStringPointer()
	alertThreshold_value := o.AlertThreshold.ValueInt64Pointer()
	blockThreshold_value := o.BlockThreshold.ValueInt64Pointer()
	logSeverity_value := o.LogSeverity.ValueStringPointer()
	var application_pango_entries []string
	if !o.Application.IsUnknown() && !o.Application.IsNull() {
		object_entries := make([]types.String, 0, len(o.Application.Elements()))
		diags.Append(o.Application.ElementsAs(ctx, &object_entries, false)...)
		if diags.HasError() {
			diags.AddError("Explicit Error", "Failed something")
			return diags
		}

		for _, elt := range object_entries {
			application_pango_entries = append(application_pango_entries, elt.ValueString())
		}
	}
	var fileType_pango_entries []string
	if !o.FileType.IsUnknown() && !o.FileType.IsNull() {
		object_entries := make([]types.String, 0, len(o.FileType.Elements()))
		diags.Append(o.FileType.ElementsAs(ctx, &object_entries, false)...)
		if diags.HasError() {
			diags.AddError("Explicit Error", "Failed something")
			return diags
		}

		for _, elt := range object_entries {
			fileType_pango_entries = append(fileType_pango_entries, elt.ValueString())
		}
	}

	if (*obj) == nil {
		*obj = new(datafiltering.Rules)
	}
	(*obj).Name = o.Name.ValueString()
	(*obj).DataObject = dataObject_value
	(*obj).Direction = direction_value
	(*obj).AlertThreshold = alertThreshold_value
	(*obj).BlockThreshold = blockThreshold_value
	(*obj).LogSeverity = logSeverity_value
	(*obj).Application = application_pango_entries
	(*obj).FileType = fileType_pango_entries

	return diags
}

func (o *DataFilteringProfileResourceModel) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *datafiltering.Entry, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var rules_list types.List
	{
		var rules_tf_entries []DataFilteringProfileResourceRulesObject
		if !o.Rules.IsNull() {
			diags.Append(o.Rules.ElementsAs(ctx, &rules_tf_entries, false)...)
			if diags.HasError() {
				return diags
			}
		}

		for idx, elt := range obj.Rules {
			entry := DataFilteringProfileResourceRulesObject{
				Name: types.StringValue(elt.Name),
			}
			if idx < len(rules_tf_entries) {
				entry = rules_tf_entries[idx]
			}

			diags.Append(entry.CopyFromPango(ctx, client, append(ancestors, entry), &elt, ev)...)
			if diags.HasError() {
				return diags
			}

			if idx < len(rules_tf_entries) {
				rules_tf_entries[idx] = entry
			} else {
				rules_tf_entries = append(rules_tf_entries, entry)
			}
		}
		var list_diags diag.Diagnostics
		schemaType := o.getTypeFor("rules")
		rules_list, list_diags = types.ListValueFrom(ctx, schemaType, rules_tf_entries)
		diags.Append(list_diags...)
	}

	var dataCapture_value types.Bool
	if obj.DataCapture != nil {
		dataCapture_value = types.BoolValue(*obj.DataCapture)
	}
	var description_value types.String
	if obj.Description != nil {
		description_value = types.StringValue(*obj.Description)
	}
	var disableOverride_value types.String
	if obj.DisableOverride != nil {
		disableOverride_value = types.StringValue(*obj.DisableOverride)
	}
	o.Name = types.StringValue(obj.Name)
	o.DataCapture = dataCapture_value
	o.Description = description_value
	o.DisableOverride = disableOverride_value
	o.Rules = rules_list

	return diags
}

func (o *DataFilteringProfileResourceRulesObject) CopyFromPango(ctx context.Context, client pangoutil.PangoClient, ancestors []Ancestor, obj *datafiltering.Rules, ev *EncryptedValuesManager) diag.Diagnostics {
	var diags diag.Diagnostics
	var application_list types.List
	{
		var list_diags diag.Diagnostics

		entries := make([]string, 0)
		if o.Application.IsNull() || len(obj.Application) > 0 {
			entries = obj.Application
		}

		application_list, list_diags = types.ListValueFrom(ctx, types.StringType, entries)
		diags.Append(list_diags...)
		if diags.HasError() {
			return diags
		}
	}
	var fileType_list types.List
	{
		var list_diags diag.Diagnostics

		entries := make([]string, 0)
		if o.FileType.IsNull() || len(obj.FileType) > 0 {
			entries = obj.FileType
		}

		fileType_list, list_diags = types.ListValueFrom(ctx, types.StringType, entries)
		diags.Append(list_diags...)
		if diags.HasError() {
			return diags
		}
	}

	var dataObject_value types.String
	if obj.DataObject != nil {
		dataObject_value = types.StringValue(*obj.DataObject)
	}
	var direction_value types.String
	if obj.Direction != nil {
		direction_value = types.StringValue(*obj.Direction)
	}
	var alertThreshold_value types.Int64
	if obj.AlertThreshold != nil {
		alertThreshold_value = types.Int64Value(*obj.AlertThreshold)
	}
	var blockThreshold_value types.Int64
	if obj.BlockThreshold != nil {
		blockThreshold_value = types.Int64Value(*obj.BlockThreshold)
	}
	var logSeverity_value types.String
	if obj.LogSeverity != nil {
		logSeverity_value = types.StringValue(*obj.LogSeverity)
	}
	o.Name = types.StringValue(obj.Name)
	o.DataObject = dataObject_value
	o.Direction = direction_value
	o.AlertThreshold = alertThreshold_value
	o.BlockThreshold = blockThreshold_value
	o.LogSeverity = logSeverity_value
	o.Application = application_list
	o.FileType = fileType_list

	return diags
}

func (o *DataFilteringProfileResourceModel) resourceXpathParentComponents() ([]string, error) {
	var components []string
	return components, nil
}

func (o *DataFilteringProfileResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var state DataFilteringProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource create", map[string]any{
		"resource_name": "panos_data_filtering_profile_resource",
		"function":      "Create",
		"name":          state.Name.ValueString(),
	})

	// Verify mode.
	if o.client.Hostname == "" {
		resp.Diagnostics.AddError("Invalid mode error", InspectionModeError)
		return
	}

	var encryptedValues []byte
	ev, err := NewEncryptedValuesManager(encryptedValues, false)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	// Determine the location.

	var location datafiltering.Location

	{
		var terraformLocation DataFilteringProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Shared.IsNull() {
			location.Shared = &datafiltering.SharedLocation{}
			var innerLocation DataFilteringProfileSharedLocation
			resp.Diagnostics.Append(terraformLocation.Shared.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.DeviceGroup.IsNull() {
			location.DeviceGroup = &datafiltering.DeviceGroupLocation{}
			var innerLocation DataFilteringProfileDeviceGroupLocation
			resp.Diagnostics.Append(terraformLocation.DeviceGroup.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.DeviceGroup.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.DeviceGroup.DeviceGroup = innerLocation.Name.ValueString()
		}
	}

	if err := location.IsValid(); err != nil {
		resp.Diagnostics.AddError("Invalid location", err.Error())
		return
	}

	// Load the desired config.
	var obj *datafiltering.Entry
	resp.Diagnostics.Append(state.CopyToPango(ctx, o.client, nil, &obj, ev)...)
	if resp.Diagnostics.HasError() {
		return
	}

	/*
		// Timeout handling.
		ctx, cancel := context.WithTimeout(ctx, GetTimeout(state.Timeouts.Create))
		defer cancel()
	*/

	// Perform the operation.

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	created, err := o.manager.Create(ctx, location, components, obj)
	if err != nil {
		resp.Diagnostics.AddError("Error in create", err.Error())
		return
	}

	resp.Diagnostics.Append(state.CopyFromPango(ctx, o.client, nil, created, ev)...)
	if resp.Diagnostics.HasError() {
		return
	}

	payload, err := json.Marshal(ev)
	if err != nil {
		resp.Diagnostics.AddError("Failed to marshal encrypted values state", err.Error())
		return
	}
	resp.Private.SetKey(ctx, "encrypted_values", payload)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (o *DataFilteringProfileResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {

	var state DataFilteringProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	encryptedValues, diags := req.Private.GetKey(ctx, "encrypted_values")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ev, err := NewEncryptedValuesManager(encryptedValues, true)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	var location datafiltering.Location

	{
		var terraformLocation DataFilteringProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Shared.IsNull() {
			location.Shared = &datafiltering.SharedLocation{}
			var innerLocation DataFilteringProfileSharedLocation
			resp.Diagnostics.Append(terraformLocation.Shared.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.DeviceGroup.IsNull() {
			location.DeviceGroup = &datafiltering.DeviceGroupLocation{}
			var innerLocation DataFilteringProfileDeviceGroupLocation
			resp.Diagnostics.Append(terraformLocation.DeviceGroup.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.DeviceGroup.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.DeviceGroup.DeviceGroup = innerLocation.Name.ValueString()
		}
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource read", map[string]any{
		"resource_name": "panos_data_filtering_profile_resource",
		"function":      "Read",
		"name":          state.Name.ValueString(),
	})

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	object, err := o.manager.Read(ctx, location, components, state.Name.ValueString())
	if err != nil {
		if errors.Is(err, sdkmanager.ErrObjectNotFound) {
			resp.State.RemoveResource(ctx)
		} else {
			resp.Diagnostics.AddError("Error reading entry", err.Error())
		}
		return
	}

	copy_diags := state.CopyFromPango(ctx, o.client, nil, object, ev)
	resp.Diagnostics.Append(copy_diags...)

	/*
			// Keep the timeouts.
		    // TODO: This won't work for state import.
			state.Timeouts = state.Timeouts
	*/

	state.Location = state.Location

	payload, err := json.Marshal(ev)
	if err != nil {
		resp.Diagnostics.AddError("Failed to marshal encrypted values state", err.Error())
		return
	}
	resp.Private.SetKey(ctx, "encrypted_values", payload)

	// Done.
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)

}
func (o *DataFilteringProfileResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {

	var plan, state DataFilteringProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	encryptedValues, diags := req.Private.GetKey(ctx, "encrypted_values")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	ev, err := NewEncryptedValuesManager(encryptedValues, false)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read encrypted values from private state", err.Error())
		return
	}

	var location datafiltering.Location

	{
		var terraformLocation DataFilteringProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Shared.IsNull() {
			location.Shared = &datafiltering.SharedLocation{}
			var innerLocation DataFilteringProfileSharedLocation
			resp.Diagnostics.Append(terraformLocation.Shared.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.DeviceGroup.IsNull() {
			location.DeviceGroup = &datafiltering.DeviceGroupLocation{}
			var innerLocation DataFilteringProfileDeviceGroupLocation
			resp.Diagnostics.Append(terraformLocation.DeviceGroup.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.DeviceGroup.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.DeviceGroup.DeviceGroup = innerLocation.Name.ValueString()
		}
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource update", map[string]any{
		"resource_name": "panos_data_filtering_profile_resource",
		"function":      "Update",
	})

	// Verify mode.
	if o.client.Hostname == "" {
		resp.Diagnostics.AddError("Invalid mode error", InspectionModeError)
		return
	}

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}
	var obj *datafiltering.Entry
	if state.Name.ValueString() != plan.Name.ValueString() {
		obj, err = o.manager.Read(ctx, location, components, state.Name.ValueString())
	} else {
		obj, err = o.manager.Read(ctx, location, components, plan.Name.ValueString())
	}
	if err != nil {
		resp.Diagnostics.AddError("Error in update", err.Error())
		return
	}

	resp.Diagnostics.Append(plan.CopyToPango(ctx, o.client, nil, &obj, ev)...)
	if resp.Diagnostics.HasError() {
		return
	}

	components, err = plan.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}

	// If name differs between plan and state, we need to set old name for the object
	// before calling SDK Update() function to properly handle rename + edit cycle.
	var newName string
	if state.Name.ValueString() != plan.Name.ValueString() {
		newName = plan.Name.ValueString()
		obj.Name = state.Name.ValueString()
	}

	updated, err := o.manager.Update(ctx, location, components, obj, newName)

	if err != nil {
		resp.Diagnostics.AddError("Error in update", err.Error())
		return
	}

	/*
		// Keep the timeouts.
		state.Timeouts = plan.Timeouts
	*/

	copy_diags := plan.CopyFromPango(ctx, o.client, nil, updated, ev)
	resp.Diagnostics.Append(copy_diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	payload, err := json.Marshal(ev)
	if err != nil {
		resp.Diagnostics.AddError("Failed to marshal encrypted values state", err.Error())
		return
	}
	resp.Private.SetKey(ctx, "encrypted_values", payload)

	// Done.
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)

}
func (o *DataFilteringProfileResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {

	var state DataFilteringProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Basic logging.
	tflog.Info(ctx, "performing resource delete", map[string]any{
		"resource_name": "panos_data_filtering_profile_resource",
		"function":      "Delete",
		"name":          state.Name.ValueString(),
	})

	// Verify mode.
	if o.client.Hostname == "" {
		resp.Diagnostics.AddError("Invalid mode error", InspectionModeError)
		return
	}

	var location datafiltering.Location

	{
		var terraformLocation DataFilteringProfileLocation
		resp.Diagnostics.Append(state.Location.As(ctx, &terraformLocation, basetypes.ObjectAsOptions{})...)
		if resp.Diagnostics.HasError() {
			return
		}

		if !terraformLocation.Shared.IsNull() {
			location.Shared = &datafiltering.SharedLocation{}
			var innerLocation DataFilteringProfileSharedLocation
			resp.Diagnostics.Append(terraformLocation.Shared.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
		}

		if !terraformLocation.DeviceGroup.IsNull() {
			location.DeviceGroup = &datafiltering.DeviceGroupLocation{}
			var innerLocation DataFilteringProfileDeviceGroupLocation
			resp.Diagnostics.Append(terraformLocation.DeviceGroup.As(ctx, &innerLocation, basetypes.ObjectAsOptions{})...)
			if resp.Diagnostics.HasError() {
				return
			}
			location.DeviceGroup.PanoramaDevice = innerLocation.PanoramaDevice.ValueString()
			location.DeviceGroup.DeviceGroup = innerLocation.Name.ValueString()
		}
	}

	components, err := state.resourceXpathParentComponents()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource xpath", err.Error())
		return
	}

	err = o.manager.Delete(ctx, location, components, []string{state.Name.ValueString()})
	if err != nil && !errors.Is(err, sdkmanager.ErrObjectNotFound) {
		resp.Diagnostics.AddError("Error in delete", err.Error())
		return
	}

}

type DataFilteringProfileImportState struct {
	Location types.Object `json:"location"`
	Name     types.String `json:"name"`
}

func (o DataFilteringProfileImportState) MarshalJSON() ([]byte, error) {
	type shadow struct {
		Location interface{} `json:"location"`
		Name     *string     `json:"name"`
	}
	var location_object interface{}
	{
		var err error
		location_object, err = TypesObjectToMap(o.Location, DataFilteringProfileLocationSchema())
		if err != nil {
			return nil, fmt.Errorf("failed to marshal location into JSON document: %w", err)
		}
	}

	obj := shadow{
		Location: location_object,
		Name:     o.Name.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *DataFilteringProfileImportState) UnmarshalJSON(data []byte) error {
	var shadow struct {
		Location interface{} `json:"location"`
		Name     *string     `json:"name"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	var location_object types.Object
	{
		location_map, ok := shadow.Location.(map[string]interface{})
		if !ok {
			return NewDiagnosticsError("Failed to unmarshal JSON document into location: expected map[string]interface{}", nil)
		}
		var err error
		location_object, err = MapToTypesObject(location_map, DataFilteringProfileLocationSchema())
		if err != nil {
			return fmt.Errorf("failed to unmarshal location from JSON: %w", err)
		}
	}
	o.Location = location_object
	o.Name = types.StringPointerValue(shadow.Name)

	return nil
}

func DataFilteringProfileImportStateCreator(ctx context.Context, resource types.Object) ([]byte, error) {
	attrs := resource.Attributes()
	if attrs == nil {
		return nil, fmt.Errorf("Object has no attributes")
	}

	locationAttr, ok := attrs["location"]
	if !ok {
		return nil, fmt.Errorf("location attribute missing")
	}

	var location types.Object
	switch value := locationAttr.(type) {
	case types.Object:
		location = value
	default:
		return nil, fmt.Errorf("location attribute expected to be an object")
	}
	nameAttr, ok := attrs["name"]
	if !ok {
		return nil, fmt.Errorf("name attribute missing")
	}

	var name types.String
	switch value := nameAttr.(type) {
	case types.String:
		name = value
	default:
		return nil, fmt.Errorf("name attribute expected to be a string")
	}

	importStruct := DataFilteringProfileImportState{
		Location: location,
		Name:     name,
	}

	return json.Marshal(importStruct)
}

func (o *DataFilteringProfileResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {

	var obj DataFilteringProfileImportState
	data, err := base64.StdEncoding.DecodeString(req.ID)
	if err != nil {
		resp.Diagnostics.AddError("Failed to decode Import ID", err.Error())
		return
	}

	err = json.Unmarshal(data, &obj)
	if err != nil {
		var diagsErr *DiagnosticsError
		if errors.As(err, &diagsErr) {
			resp.Diagnostics.Append(diagsErr.Diagnostics()...)
		} else {
			resp.Diagnostics.AddError("Failed to unmarshal Import ID", err.Error())
		}
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("location"), obj.Location)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), obj.Name)...)
}

type DataFilteringProfileSharedLocation struct {
}
type DataFilteringProfileDeviceGroupLocation struct {
	PanoramaDevice types.String `tfsdk:"panorama_device"`
	Name           types.String `tfsdk:"name"`
}
type DataFilteringProfileLocation struct {
	Shared      types.Object `tfsdk:"shared"`
	DeviceGroup types.Object `tfsdk:"device_group"`
}

func DataFilteringProfileLocationSchema() rsschema.Attribute {
	return rsschema.SingleNestedAttribute{
		Description: "The location of this object.",
		Required:    true,
		Attributes: map[string]rsschema.Attribute{
			"shared": rsschema.SingleNestedAttribute{
				Description: "Panorama shared object",
				Optional:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},

				Validators: []validator.Object{
					objectvalidator.ExactlyOneOf(path.Expressions{
						path.MatchRelative().AtParent().AtName("shared"),
						path.MatchRelative().AtParent().AtName("device_group"),
					}...),
				},
			},
			"device_group": rsschema.SingleNestedAttribute{
				Description: "Located in a specific Device Group",
				Optional:    true,
				Attributes: map[string]rsschema.Attribute{
					"panorama_device": rsschema.StringAttribute{
						Description: "Panorama device name",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("localhost.localdomain"),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"name": rsschema.StringAttribute{
						Description: "Device Group name",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString(""),
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
				},
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

func (o DataFilteringProfileSharedLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
	}

	obj := shadow{}

	return json.Marshal(obj)
}

func (o *DataFilteringProfileSharedLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}

	return nil
}
func (o DataFilteringProfileDeviceGroupLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	obj := shadow{
		PanoramaDevice: o.PanoramaDevice.ValueStringPointer(),
		Name:           o.Name.ValueStringPointer(),
	}

	return json.Marshal(obj)
}

func (o *DataFilteringProfileDeviceGroupLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		PanoramaDevice *string `json:"panorama_device,omitempty"`
		Name           *string `json:"name,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	o.PanoramaDevice = types.StringPointerValue(shadow.PanoramaDevice)
	o.Name = types.StringPointerValue(shadow.Name)

	return nil
}
func (o DataFilteringProfileLocation) MarshalJSON() ([]byte, error) {
	type shadow struct {
		Shared      *DataFilteringProfileSharedLocation      `json:"shared,omitempty"`
		DeviceGroup *DataFilteringProfileDeviceGroupLocation `json:"device_group,omitempty"`
	}
	var shared_object *DataFilteringProfileSharedLocation
	{
		diags := o.Shared.As(context.TODO(), &shared_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal shared into JSON document", diags.Errors())
		}
	}
	var deviceGroup_object *DataFilteringProfileDeviceGroupLocation
	{
		diags := o.DeviceGroup.As(context.TODO(), &deviceGroup_object, basetypes.ObjectAsOptions{})
		if diags.HasError() {
			return nil, NewDiagnosticsError("Failed to marshal device_group into JSON document", diags.Errors())
		}
	}

	obj := shadow{
		Shared:      shared_object,
		DeviceGroup: deviceGroup_object,
	}

	return json.Marshal(obj)
}

func (o *DataFilteringProfileLocation) UnmarshalJSON(data []byte) error {
	var shadow struct {
		Shared      *DataFilteringProfileSharedLocation      `json:"shared,omitempty"`
		DeviceGroup *DataFilteringProfileDeviceGroupLocation `json:"device_group,omitempty"`
	}

	err := json.Unmarshal(data, &shadow)
	if err != nil {
		return err
	}
	var shared_object types.Object
	{
		var diags_tmp diag.Diagnostics
		shared_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.Shared.AttributeTypes(), shadow.Shared)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into shared", diags_tmp.Errors())
		}
	}
	var deviceGroup_object types.Object
	{
		var diags_tmp diag.Diagnostics
		deviceGroup_object, diags_tmp = types.ObjectValueFrom(context.TODO(), shadow.DeviceGroup.AttributeTypes(), shadow.DeviceGroup)
		if diags_tmp.HasError() {
			return NewDiagnosticsError("Failed to unmarshal JSON document into device_group", diags_tmp.Errors())
		}
	}
	o.Shared = shared_object
	o.DeviceGroup = deviceGroup_object

	return nil
}

func (o *DataFilteringProfileSharedLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{}
}
func (o *DataFilteringProfileDeviceGroupLocation) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"panorama_device": types.StringType,
		"name":            types.StringType,
	}
}
func (o *DataFilteringProfileLocation) AttributeTypes() map[string]attr.Type {
	var sharedObj DataFilteringProfileSharedLocation
	var deviceGroupObj DataFilteringProfileDeviceGroupLocation
	return map[string]attr.Type{
		"shared": types.ObjectType{
			AttrTypes: sharedObj.AttributeTypes(),
		},
		"device_group": types.ObjectType{
			AttrTypes: deviceGroupObj.AttributeTypes(),
		},
	}
}
